apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage # Fixed label
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage # Fixed label
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "home.pobournex,192.168.40.152"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config/settings.yaml
          subPath: settings.yaml
        - name: config-volume
          mountPath: /app/config/services.yaml
          subPath: services.yaml
        - name: config-volume
          mountPath: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
        - name: config-volume
          mountPath: /app/config/widgets.yaml
          subPath: widgets.yaml
        - name: config-volume
          mountPath: /app/config/kubernetes.yaml
          subPath: kubernetes.yaml
      volumes:
      - name: config-volume
        configMap:
          name: homepage-config
