apiVersion: v1
kind: Service
metadata:
  name: homepage  # Ensure this is just "homepage"
  namespace: homepage
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.40.152
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: homepage  # This must match your pod labels!
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
