apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: stirling-pdf-route
  namespace: traefik  # <--- Change this to match Traefik's namespace
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`pdf.pobournex`)
      kind: Rule
      services:
        - name: stirling-pdf-service
          namespace: default # <--- Explicitly tell Traefik the service is in default
          port: 80
