apiVersion: apps/v1
kind: Deployment
metadata:
  name: stirling-pdf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stirling-pdf
  template:
    metadata:
      labels:
        app: stirling-pdf
    spec:
      containers:
      - name: stirling-pdf
        image: frooodle/s-pdf:latest
        ports:
        - containerPort: 8080
        env:
        - name: DOCKER_ENABLE_SECURITY
          value: "false" # Set to true later if you want a login page
        - name: INSTALL_BOOK_AND_ADVANCED_HTML_OPS
          value: "true"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: stirling-pdf-service
  namespace: default
spec:
  selector:
    app: stirling-pdf
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
